### ISSUE TITLE
Invalid compressed stream after flushing empty input stream

### ISSUE THREAD

**Issue by jscheid** [alexcrichton/flate2-rs#108]
Hi, thanks for a nice lib! Works really well, apart from this one issue I'm having.

Running the code below with Flate 0.2.19 and Apple gzip 264.50.1 gives me:

```
gunzip: unknown compression format
exit code: 1
```

It seems that flushing before writing data seems to cause the output stream to become corrupted. 

I'd expect the writer to always work no matter how often or at what times `flush` is called. 

FWIW, I've experimented with calling `flush` and `try_finish` in various combinations and got slightly different results. Perhaps you would also want to check that calling `try_finish` on an empty input works as expected.

```rust
use std::process::{Command, Stdio};
use std::io::Write;
use flate2::{Compression, GzBuilder};

fn main() {
    let mut child = Command::new("gunzip")
        .arg("-c")
        .stdin(Stdio::piped())
        .spawn()
        .unwrap();
    {
        let mut encoder = GzBuilder::new()
            .write(child.stdin.take().unwrap(), Compression::Fast);

        // comment out the following line and gunzip will happily decode
        encoder.flush().unwrap();
        encoder.write("Hello World!\n".to_string().as_bytes()).unwrap();
    }
    println!("{}", child.wait().unwrap());
}
```

**Comment by alexcrichton** [comment]
Thanks for the report!
