### ISSUE TITLE
API doesn't expose individual compression levels

### ISSUE THREAD

**Issue by fstirlitz** [alexcrichton/flate2-rs#112]
The `Compression` type is an enum which may only take four values: `None`, `Fast`, `Best` and `Default`. Both zlib and miniz backends allow at least ten compression levels in their API (apparently miniz goes to eleven), but this crate doesn't allow specifying levels other than those four.

(The reason I want this feature is that I wish to support an interface which already exposes those levels to the user.)

**Comment by alexcrichton** [comment]
Thanks for the report! I've often thought that an enum wasn't the best choice here as well. I'm thinking that I may switch to an opaque struct which can be constructed from any value in the 1.0 release
