### ISSUE TITLE
flate2::write::GzDecoder missing

### ISSUE THREAD

**Issue by AndyGauge** [alexcrichton/flate2-rs#113]
Is there supposed to be a GzDecoder that implements Write?  I don't need it for anything, it just seemed like it was overlooked.

**Comment by alexcrichton** [comment]
There is indeed supposed to be a struct that does it! I just never got around to figuring out the best interface for this, though :(

**Comment by vandenoever** [comment]
I came across this issues because for my application, I need `write::GzDecoder`. Since decompression does not require parameters a struct that implements the `Write` trait and is constructed with a `new<W: Write>(w: W) -> GzDecoder<W>` should do it.

**Comment by alexcrichton** [comment]
A bit late to the punch, but added in https://github.com/alexcrichton/flate2-rs/pull/132
