### ISSUE TITLE
Expose EncoderWriter to be public

### ISSUE THREAD

**Issue by MicroJoe** [alexcrichton/flate2-rs#116]
Hello, I am playing with your crate and I am trying to implement a generic wrapper function that looks like this:

```rust
fn compress<E: EncoderWriter>(data: &[u8], e: &mut E) {
    e.write(data);
    let compressed_bytes = e.finish().unwrap();

    println!("Compressed is {} bytes", compressed_bytes.len());
}

fn main() {
    // ...

    let mut e = ZlibEncoder::new(Vec::new(), Compression::Default);
    compress(buffer.as_slice(), e);
}
```

However I cannot import the `EncoderWriter` trait so I cannot make this generic function work. Maybe I am missing something.

**Comment by dmizuk** [comment]
There is no *trait* named `EncoderWriter` (either publicly or privately). It is an internal name for different *struct*s.

https://github.com/alexcrichton/flate2-rs/blob/2b324f65d27a89ebc391aa56abfd6a6ff20ce39a/src/lib.rs#L152-L158

**Comment by MicroJoe** [comment]
I see, I only looked one source file and thought that this was generic. Is there any chance for the encoders to share a common trait or something like that to allow generics and be able to easily switch between Gzip, Deflate and Zlib?

**Comment by dmizuk** [comment]
How about monkey-patching them?

```rust
use std::io::{Result, Write};

trait Flate2EncoderExt<W: Write>: Write {
    fn finish(self) -> Result<W>;
}

impl<W: Write> Flate2EncoderExt<W> for DeflateEncoder<W> {
    fn finish(self) -> Result<W> {
        self.finish()
    }
}

// and so on
```

**Comment by alexcrichton** [comment]
Ah so currently "The Trait" intended for abstraction is `Read` or `Write`, but it doesn't cover the `finish`-style methods, yeah. Currently I'd prefer to avoid premature abstraction with such a trait, but if there's a solid reason for doing so I could consider adding it!

**Comment by MicroJoe** [comment]
I have managed to write my microbenchmark code using this abstraction @dmizuk proposed:

```rust
extern crate byteorder;
extern crate flate2;

use std::fs::File;
use std::io::prelude::*;
use byteorder::{LittleEndian, WriteBytesExt};

use std::io::{Result, Write};

use flate2::Compression;
use flate2::write::ZlibEncoder;
use flate2::write::DeflateEncoder;
use flate2::write::GzEncoder;

#[derive(Debug)]
struct Point {
    x: i16,
    y: i16
}

type MyOrder = LittleEndian;

trait Flate2EncoderExt<W: Write>: Write {
    fn name() -> &'static str;
    fn finish(self) -> Result<W>;
}

impl<W: Write> Flate2EncoderExt<W> for DeflateEncoder<W> {
    fn name() -> &'static str {
        "deflate"
    }
    fn finish(self) -> Result<W> {
        DeflateEncoder::finish(self)
    }
}

impl<W: Write> Flate2EncoderExt<W> for ZlibEncoder<W> {
    fn name() -> &'static str {
        "zlib"
    }
    fn finish(self) -> Result<W> {
        ZlibEncoder::finish(self)
    }
}

impl<W: Write> Flate2EncoderExt<W> for GzEncoder<W> {
    fn name() -> &'static str {
        "gz"
    }
    fn finish(self) -> Result<W> {
        GzEncoder::finish(self)
    }
}

fn compress<T: Flate2EncoderExt<Vec<u8>>>(mut compressor: T, buffer: &[u8]) {
    compressor.write(buffer);
    let result = compressor.finish();
    println!("[{}] Size is {} bytes", T::name(), result.unwrap().len());
}

fn main() {
    let pt = Point { x: 42, y: 2 };
    let mut buffer = vec![];

    println!("Hello, world!");
    println!("{:?}", pt);

    for i in 0..4442 {
        buffer.write_i16::<MyOrder>(pt.x).unwrap();
        buffer.write_i16::<MyOrder>(pt.y).unwrap();
    }

    println!("Uncompressed is {} bytes", buffer.len());

    let mut deflate_compressor = DeflateEncoder::new(Vec::new(), Compression::Default);
    compress(deflate_compressor, buffer.as_slice());

    let mut zlib_compressor = ZlibEncoder::new(Vec::new(), Compression::Default);
    compress(zlib_compressor, buffer.as_slice());

    let mut gzip_compressor = GzEncoder::new(Vec::new(), Compression::Default);
    compress(gzip_compressor, buffer.as_slice())
}
```

```
Hello, world!
Point { x: 42, y: 2 }
Uncompressed is 17768 bytes
[deflate] Size is 38 bytes
[zlib] Size is 44 bytes
[gz] Size is 56 bytes
```

However if I want to make the main code even more readable I want to make the following changes in the trait:

```rust
trait Flate2EncoderExt<W: Write>: Write {
    fn name() -> &'static str;
    fn default() -> Flate2EncoderExt<W>;
    fn finish(self) -> Result<W>;
}
```

However a trait cannot return itself and is this denied by the compiler. The idea was to implement it like this:

```rust
impl<W: Write> Flate2EncoderExt<W> for DeflateEncoder<W> {
    fn name() -> &'static str {
        "deflate"
    }
    fn finish(self) -> Result<W> {
        DeflateEncoder::finish(self)
    }
    fn default() -> Flate2EncoderExt<W> {
        DeflateEncoder::new(Vec::new(), Compression::Default)
    }
}
```

In order to avoid to repeat code for creating each "compressor" I want to use. I think I am reaching the limit of monkey patching this.

**Comment by oyvindln** [comment]
For your example, maybe a simpler way to solve it would be to have a function that wraps the writer creation, write call (you should probably use write_all by the way, write won't write all the data if there is a lot of data), and finish call like I have in [deflate](https://github.com/oyvindln/deflate-rs/blob/dev/src/lib.rs#L156). With that the compress function could take a `&[u8] -> Vec<u8>` function (and optionally a name string) rather than a trait as an argument.

That said a trait that could be implemented by this, and other compression formats may have uses.

(Also, not sure if this is the case here, but in case it's not clear from the documentation: Gzip and zlib are simply different wrappers for deflate-compressed data, contaning metadata and a checksum, The compressed data will be the same regardless of which of `DeflateEncoder` (which is just the raw compressed stream with no extra info),`ZlibEncoder` and `GzipEncoder` you use.)

**Comment by alexcrichton** [comment]
I'm going to close this for now as I'd personally prefer to avoid exposing this trait, but thanks for the report!
