### ISSUE TITLE
Some problems

### ISSUE THREAD

**Issue by Valaquend** [alexcrichton/flate2-rs#12]
1, the `io` in README.md `use std::io::MemWriter;` should now be changed to `old_io`.

2, you did not put `CompressionLevel::Default` into `pub use CompressionLevel::{BestCompression,BestSpeed,NoCompression};`, so the example in README.md might be
```
let mut e = ZlibEncoder::new(MemWriter::new(), flate2::CompressionLevel::Default);
```

3, By the way, i'm going to write a distributed nosql using rust.  Is flate2 suitable for data storage and should i use BestSpeed or Default?
// Forgive me, my english is not very good :)

**Comment by alexcrichton** [comment]
> the io in README.md use std::io::MemWriter; should now be changed to old_io

Oops, thanks for the pointer!

>  Is flate2 suitable for data storage and should i use BestSpeed or Default?

I suppose it depends on how much you're storing data and how much data you're storing. If you frequently need to compress then `BestSpeed` may be the way to go, but if you store rarely and have tons of stored data you may want `Default`.

You can likely tune based on your applications needs over time, I'd wait to see where the bottlenecks are!
