### ISSUE TITLE
Z_STREAM_ERROR not handled in Compress::compress

### ISSUE THREAD

**Issue by luser** [alexcrichton/flate2-rs#122]
I tried running the tests for my `mszip` crate on my updated Ubuntu machine for the first time, and it hits a panic in flate2:
thread 'main' panicked at 'unknown return code: -2', /home/luser/.cargo/git/checkouts/flate2-rs-694405718fd981f8/31eca0c/src/mem.rs:231

This is because [`Compress::compress`](https://github.com/alexcrichton/flate2-rs/blob/d4168a52d4d8e129cce73ab1c2c87e765c39ba57/src/mem.rs#L235) doesn't handle [`Z_STREAM_ERROR`](https://github.com/alexcrichton/libz-sys/blob/b4b3ead55cc164ab8bf4ce90f7c9db6ca65bc95e/src/lib.rs#L214).

**Comment by alexcrichton** [comment]
Oh dear this sounds bad...

What does `Z_STREAM_ERROR` mean in this context? I thought you couldn't fail when compressing :(

**Comment by alexcrichton** [comment]
Er in that in theory this never comes up, so this may indicate a bug in the library instead where we're calling libz in the wrong order somewhere.

**Comment by luser** [comment]
Sorry, to be clear, I don't think the fact that this *happens* is a bug in flate2. The caller here is my code that is [poking into the raw zlib context ](https://github.com/luser/rust-makecab/blob/7eb27ba11b8909a1e2c01b63510e1f1c989912c8/mszip/src/lib.rs#L124) to call niche zlib functions. It's very likely that something there is wrong (although it worked on an earlier version of zlib). I just found the `panic!` inside flate2 a bit unfriendly, although for things that can't happen in normal usage maybe it's OK!

**Comment by alexcrichton** [comment]
Aha!

I think then perhaps that it may be best to modify this function to return a `Result` instead and have all internal callers use `.unwrap()` as it shouldn't fail and then external callers would handle errors themselves perhaps?
