### ISSUE TITLE
Put gzip support behind a feature

### ISSUE THREAD

**Issue by oyvindln** [alexcrichton/flate2-rs#124]
My thought is that since flate2 is now used when building rust, having the gzip code behind a feature might be nice, so it can be disabled for crates that don't use it (like rustc) to cut down on compile time.

**Comment by alexcrichton** [comment]
Can you quantify the amount of build time attributed to gz support?

**Comment by alexcrichton** [comment]
I'm going to close this for now as I don't think there's much benefit to be gained, but let me know if I'm wrong!
