### ISSUE TITLE
`write::DeflateDecoder` implementing `Read` can lead to very confusing bugs

### ISSUE THREAD

**Issue by Migi** [alexcrichton/flate2-rs#125]
When I first started using this crate, I added this line to my code:

```
use flate2::write::*;
```

This lead to a *lot* of confusion later on when my `DeflateDecoder` and my `ZlibDecoder` were simply not decoding anything. They would compile without warning, and behave like a perfectly normal stream, but they just weren't decoding the data.

Of course the problem is that those `DeflateDecoder` and `ZlibDecoder` are from the `write` module, not from the `read` module. And, as I found out the hard way, `write::DeflateDecoder` and `write::ZlibDecoder` *do* implement `Read` if the underlying stream is `Read` (such as a `std::fs::File`), but implement this simply by reading the underlying stream undecoded.

None of this is mentioned in the docs.

Now, all of this might be by design. But if so, this pitfall deserves a bit more attention in the docs. If it's not intended design, then you could consider making decoders in the `write` module either read decoded data, or not implement `Read` at all.

I haven't tested it but I believe the same remarks hold also for encoders in the `read` module implementing `Write`.

[Here's a playground example demonstrating the "bug".](https://play.rust-lang.org/?gist=008620eddebc43d683cf727d680a32cc)

**Comment by alexcrichton** [comment]
Yes this is by design, but sounds like it's worth mentioning in the docs!

**Comment by KodrAus** [comment]
Do you think a comment in the [Organization section](https://docs.rs/flate2/0.2.20/flate2/index.html#organization) in the crate root about being careful to use the types under the `read` module for decoding and `write` module for encoding be enough here?

**Comment by alexcrichton** [comment]
Seems reasonable to me!
