### ISSUE TITLE
`read_to_end()` returns an Error even though the decoding was successful

### ISSUE THREAD

**Issue by Migi** [alexcrichton/flate2-rs#126]
Encoding some data to a `Vec<u8>`, then decoding the resulting `Vec<u8>` using `read_to_end()` returns an `Error`, even though it successfully decodes the data.

Link to a playground example demonstrating the issue: https://play.rust-lang.org/?gist=acca438d551a3bf66ae0025c7d987009

**Comment by alexcrichton** [comment]
Thanks for the report! This is a case though where you'll need to use the `finish` function instead of the `flush_finish` function. The `flush_*` variant is a different form of flushing, whereas the `finish` function entirely completes the stream.

**Comment by Migi** [comment]
My apologies. I used `flush_finish` without properly reading its docs, so this was a pretty clear case of [PEBCAK](https://en.wiktionary.org/wiki/PEBCAK).
