### ISSUE TITLE
Document care using types under read for writing

### ISSUE THREAD

**Issue by KodrAus** [alexcrichton/flate2-rs#127]
To clarify the behaviour noted in https://github.com/alexcrichton/flate2-rs/issues/125

Add some documentation to the [Organisation section](https://docs.rs/flate2/0.2.20/flate2/index.html#organization) to only use types under the `read` module for decoding and types under the `write` module for encoding. Rust won't fail to build if you `Read` from a type under `write` or vice-versa because they also implement `Read`. It just won't do what you expect at runtime.

**Comment by alexcrichton** [comment]
👍
