### ISSUE TITLE
Can encoders work with &mut references that implement Writer?

### ISSUE THREAD

**Issue by mikedilger** [alexcrichton/flate2-rs#13]
```fn new(w: W, level: CompressionLevel) -> EncoderWriter<W>``` consumes w.   Is that necessary?  I have a situation with an ```&mut BufferedStream``` which doesn't implement Writer because it's a borrowed reference, not the thing itself.   I have to hack around with a ```MemWriter```, and then writing the ``memory.get_ref()``` into my ```&mut Buffered Stream```.  I'd rather be able to call ```DeflateEncoder::new( w , CompressionLevel::Default)``` (or similar) with the &mut BufferedStream.

**Comment by alexcrichton** [comment]
You should be able to do this yeah. You can use `.by_ref()` but `&mut W` where `W: Writer` should also satisfy this. Note that this may require some upstream changes to I/O, but I think that regardless `.by_ref()` should do the trick for you today.
