### ISSUE TITLE
Seekable gzip Streams

### ISSUE THREAD

**Issue by SoniEx2** [alexcrichton/flate2-rs#140]
Would it be possible to support seekable gzip streams if the underlying stream is also seekable?

**Comment by alexcrichton** [comment]
I don't believe so, no (although I could be missing something in zlib)

**Comment by SoniEx2** [comment]
Non-zlib?

**Comment by alexcrichton** [comment]
Not that I know of

**Comment by SoniEx2** [comment]
Ok. Thanks anyway.
