### ISSUE TITLE
Compression level has no effect on ZlibEncoder write

### ISSUE THREAD

**Issue by alex-chung** [alexcrichton/flate2-rs#147]
I tried [zlibencoder-write.rs](https://github.com/alexcrichton/flate2-rs/blob/master/examples/zlibencoder-write.rs) example with different compression levels (none, default, fast, and best), and the result is the same for all levels.

**Comment by alexcrichton** [comment]
What content are you encoding? Perhaps it's small enough that zlib doesn't change based on the level?

**Comment by alex-chung** [comment]
I tried it with bytes from an 40 MB file. The output still has [0x78, 0x01] as the first two bytes indicates the lowest compression level.

**Comment by alexcrichton** [comment]
Can you provide an example test case for this?

**Comment by oyvindln** [comment]
Those two first bytes are the zlib header structure. The compression level flag in the header doesn't actually do anything, so miniz [is lazy](https://github.com/alexcrichton/flate2-rs/blob/master/miniz-sys/miniz.c#L2223) and just writes the same values no matter the compression level. It doesn't have any bearing on the actual compression level.

**Comment by alex-chung** [comment]
With the larger file, there does seem to be difference in compression, although the zlib header is the same.
