### ISSUE TITLE
Add a method on Compress to dynamically update compression level.

### ISSUE THREAD

**Issue by quadrupleslap** [alexcrichton/flate2-rs#153]
I don't know if this is possible, but it'd be nice if I could reuse `Compress` at a different compression level.

**Comment by quadrupleslap** [comment]
I think ZLIB has `deflateParams` for this, but I can't find any equivalent in `miniz[_oxide]`.

**Comment by alexcrichton** [comment]
Oh nice! I think this'd also be fine as a zlib-only feature
