### ISSUE TITLE
Wasm support

### ISSUE THREAD

**Issue by wehlutyk** [alexcrichton/flate2-rs#161]
Hi!

There is discussion over at Frommi/miniz_oxide#34 (and previously Frommi/miniz_oxide#26) to support Wasm for `miniz_oxide_c_api` (on top of `miniz_oxide`) using the libc-stub hack from [alexcrichton/wasm-sodium](https://github.com/alexcrichton/wasm-sodium). From there, it's only a [small addition to flate2-rs](https://github.com/wehlutyk/flate2-rs/commit/f40cfc39689fb92e50fbe62375384ea23d764d26#diff-b4aea3e418ccdb71239b96952d9cddb6) to make this crate compile to wasm32. Would you take that as PR, or would you rather wait until libc has an implementation for wasm32?

**Comment by alexcrichton** [comment]
Sounds like a great idea to me!

I think we should enable the rust-backend feature by default on wasm to make sure `flate2` builds by default on wasm as well!

**Comment by wehlutyk** [comment]
Great!

Ah yes, the rust_backend thing would be nice. I currently have to surface that feature through client crates of `flate2-rs` such as `lopdf`.

Will be back once the miniz_oxide change is made.

**Comment by wehlutyk** [comment]
Correction: I can't find a way to set a default feature for a given target. Are you referring to rust-lang/cargo#1197?

**Comment by alexcrichton** [comment]
Nah we'd just hardcode this in the code, an unconditional target-specific dependency would be added for wasm and then on wasm the code would unconditionally (regardless of features) use miniz_oxide

**Comment by alexcrichton** [comment]
This should be implemented now!
