### ISSUE TITLE
Directly use miniz_oxide

### ISSUE THREAD

**Issue by infinity0** [alexcrichton/flate2-rs#181]
In Debian we're patching away usage of miniz and miniz_oxide because it's simpler to just use the system zlib. The "rust_backend" feature actually just points to zlib.

If flate2/rust_backend uses miniz_oxide directly (rather than through miniz_oxide_c_api) then it would be easier to have a "real" rust_backend actually in Debian.

**Comment by oyvindln** [comment]
Yeah that would be preferable. Using it via the c api wrapper was mainly to make it easy to add support for it while keeping support for the c backends. Using it directly required some larger changes to flate2. The C Api is a bit iffy and has a fair bit of unsafe in it due it being a C API

**Comment by oyvindln** [comment]
I've started working on this now, after removing all unsafe usage in the miniz_oxide core crate.
