### ISSUE TITLE
Performance regression?

### ISSUE THREAD

**Issue by nerdrew** [alexcrichton/flate2-rs#19]
I updated rust / cargo / flate2 to the most recent versions and un-gzipping a small (165B) file takes multiple seconds. Is it me or did something change?

versions:
```
% rustc --version
rustc 1.0.0-nightly (199bdcfef 2015-03-26) (built 2015-03-26)
% cargo --version
cargo 0.0.1-pre-nightly (9f265c8 2015-03-25) (built 2015-03-26)

   Compiling miniz-sys v0.1.4
   Compiling flate2 v0.2.1
```

**Comment by alexcrichton** [comment]
Do you have a test case I could profile with? Alternatively, do you have a profile I could look at?

This may also be fixed by https://github.com/rust-lang/rust/pull/23820

**Comment by nerdrew** [comment]
I don't have a test case right this second, but it is almost certainly the same issue, since I'm using `read_to_end`

**Comment by alexcrichton** [comment]
Ok! closing in favor of that then :)

**Comment by nerdrew** [comment]
Hmmm. The speed depends on the size of the buffer passed into `read_to_end`

https://github.com/nerdrew/slow_rust_read_to_end

**Comment by alexcrichton** [comment]
Upon profiling it looks like 97% of the runtime is spent in io::Read::read_to_end, so I think that this is definitely  rust-lang/rust#23820
