### ISSUE TITLE
Decompress example

### ISSUE THREAD

**Issue by Keats** [alexcrichton/flate2-rs#191]
Hi!

I am trying to do a streaming decompression where I get a bunch of bytes and want to process them immediately without the complete file in memory as it can get huge (20gb+).
Those bytes are coming from a multipart upload so I don't think I can get a bufreader from that.
I'm already using the `Compress` struct to have streaming gzip so I thought of using the `Decompress` struct but I am getting an error:

```rust
let mut test = Vec::with_capacity(6400);
let res = flate2::Decompress::new(false).decompress_vec(&buf, &mut test, flate2::FlushDecompress::None);
println!("{:?}", res);
```
will print: `Err(DecompressError(DecompressErrorInner { needs_dictionary: None }))`

In that example, this is a test where I'm passing 32 bytes at a time.

What am I missing? Ideally I would use `MultiGzDecoder`, append some bytes and extract the un-gzipped stream as if I was using a bufreader

**Comment by wbrickner** [comment]
Did you find a solution? Please provide it next time
