### ISSUE TITLE
Possible performance regression between versions 0.2.20 and 1.0.7

### ISSUE THREAD

**Issue by pylaligand** [alexcrichton/flate2-rs#193]
While working on a program that handles compressed tarballs, I noticed a pretty steep performance regression after switching to version 1.0.7 of flate2.

Here's a small program that demonstrates the issue:
```rust
use std::env;
use std::fs::File;
use std::time::Instant;

use failure::Error;
use flate2::read::GzDecoder;
use tar::Archive;

fn main() -> Result<(), Error> {
    let args: Vec<String> = env::args().collect();
    let tar_gz_path = &args[1];
    let tar_gz = File::open(&tar_gz_path)?;
    let tar = GzDecoder::new(tar_gz)?;  // Note: remove the ? operator with 1.0.7.
    let mut archive = Archive::new(tar);
    let entries = archive.entries()?;

    let now = Instant::now();

    entries
        .filter_map(|entry| { entry.ok() })
        .for_each(|entry| {
            entry.path().unwrap();
        });

    println!("Took {} seconds.", now.elapsed().as_secs());

    Ok(())
}
```

The archive I used for testing is 86M with about 800 files (available at https://drive.google.com/open?id=1mQ1rUd2rPcXI0nqYLTgtuOxNVp1FZbOQ). The timing results are:
- 0.2.20: 3 seconds
- 1.0.7: 30 seconds

/cc @alexcrichton, @cramertj

**Comment by alexcrichton** [comment]
Thanks for the report! Can you perhaps provide some more information how to reproduce? Locally on my machine the results I see is that on master it the program takes ~800ms whereas previously on 0.2.20 (the tagged commit) it takes 1.9s. I'm running on x86_64 Linux and this is with the miniz backend. Are you perhaps on a different platform and/or running with a different backend?

**Comment by pylaligand** [comment]
I'll have the same performance improvement please :)

I'm on the same platform. As for the backend, I'm not explicitly requesting zlib or the Rust one via Cargo.toml so I guess I'm on miniz as well? Is there any way to verify I am?

**Comment by alexcrichton** [comment]
Hm ok, so [these are the test files I was using](https://gist.github.com/alexcrichton/297501fe62a41ab39ce17a3026032407) and the timings I get are:

```
$ cargo run --release ../flate2-rs/rust_flate2_perf_regression.gz
    Finished release [optimized] target(s) in 0.02s
     Running `target/release/wut ../flate2-rs/rust_flate2_perf_regression.gz`
flate2 0.2.20 took 1.357231056s.
flate2 1.0.7 took 784.678576ms.
$ cargo run --features zlib --release ../flate2-rs/rust_flate2_perf_regression.gz
    Finished release [optimized] target(s) in 0.02s
     Running `target/release/wut ../flate2-rs/rust_flate2_perf_regression.gz`
flate2 0.2.20 took 928.456151ms.
flate2 1.0.7 took 759.291956ms.
$ md5sum ../flate2-rs/rust_flate2_perf_regression.gz
707240e615f663dc4ef8c1c9f5f62b46  ../flate2-rs/rust_flate2_perf_regression.gz
```

If you don't explicitly activate any features (and you're the only crate depending on flate2 so there's nothing else in play) then the miniz backend should be used by default. You should be able to test out that program locally though to see what's going on.

**Comment by pylaligand** [comment]
I'm getting similar results when building the test program with `cargo`:
```
flate2 0.2.20 took 1.819789554s.
flate2 1.0.7 took 1.029916683s.
```

I previously built it using Fuchsia's build system. This suggests an issue with how we produce our Rust binaries there, not with the crate itself.

Thanks for your help!
