### ISSUE TITLE
Infinite loop

### ISSUE THREAD

**Issue by nilgoyette** [alexcrichton/flate2-rs#197]
I'm trying to open a big 4D images with [nifti-rs](https://github.com/Enet4/nifti-rs), which uses `flate2::bufread::GzDecoder` to decode the .nii.gz files. It always work flawlessly, except this time the image is bigger and the loading never ends. I tested on Windows and Linux, the behavior is the same: it goes on until the program uses a little less than 4GB, then it stops asking for more memory but it still uses one thread.

**I tested with 7zip and other programs and the archive is valid.** nifti-rs is able to read it when uncompressed. So, my first solution was to modify [nifti-rs](https://github.com/Enet4/nifti-rs/blob/master/src/volume/inmem.rs#L69)

```
// I replaced this line
source.read_exact(&mut raw_data)?;
// by
for mut chunk in raw_data.chunks_mut(1024) {
    source.read_exact(&mut chunk)?;
}
```
and it does work! However, the situation is still highly suspicious, so I searched and possibly found the problem in [`read` (`zio.rs`)](https://github.com/alexcrichton/flate2-rs/blob/master/src/zio.rs#L118). I printed these four variables, which look important ;)

```
    before_in   before_out    read    consumed
       294          352       32416        0
       294        32768      644285     7888
      8182       677053      155534     8192
     16374       832587       96569     8192
     24556       929156       80077     8192
     32758      1009233      149304     8192
     40950      1158537       16695     8192
.............. when it hangs ...............
1125367798   3932499552           0        0
1125367798   3932499552           0        0
1125367798   3932499552           0        0
... afaik, it stays like that ...
```
I don't know much about this codebase, but `read == 0 && !eof` can mean an infinite loop. And I'm pretty sure it does in this case. My file weights 2.2Gb, do you need it?

**Comment by alexcrichton** [comment]
Thanks for the report! Would it be possible to share the file in question to help dig into what's going on?

**Comment by nilgoyette** [comment]
Of course. https://drive.google.com/open?id=1UzeaUQ6dwRbD3TlFooay_5Nc7wagNhc- I'll leave it as long as this issue is open.

**Comment by alexcrichton** [comment]
Ok I got the file but a small program to try to reproduce this which just decompresses it doesn't exhibit the same issue seen here. Is this perhaps a misbehaving underlying buffered reader? Would it be possible to share a small snippet to reproduce this?

**Comment by nilgoyette** [comment]
Yes, you can use my fork of nifti-rs https://github.com/nilgoyette/nifti-rs/tree/flate_loop
`cargo run --bin bug --release --features ndarray_volumes -- path/to/599469__dwi_iso.nii.gz`

I just tested on windows with this branch and I have the infinite loop problem.

**Comment by alexcrichton** [comment]
Ok ended up tracking it down to a bad cast which caused truncation, shame on me for adding that in!
