### ISSUE TITLE
invalid gzip header

### ISSUE THREAD

**Issue by adjivas** [alexcrichton/flate2-rs#21]
Hi @alexcrichton and thank you for your work.

I have tried your library with the standards ***2to3-2.6.1*****.gz** format but I have getted this incident:

```shell
$ rustc -V
rustc 1.0.0-beta (9854143cb 2015-04-02) (built 2015-04-02)
$ cargo run
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Custom(Custom { kind: InvalidInput, error: StringError("invalid gzip header") }) }', /home/rustbuild/src/rust-buildbot/slave/beta-dist-rustc-linux/build/src/libcore/result.rs:774
An unknown error occurred
```
By consequent, I report for you my main.rs' test:
```rust
extern crate flate2;

use std::io::prelude::*;
use flate2::read::GzDecoder;

fn main() {
    let mut d = GzDecoder::new("/usr/share/man/man1/2to3-2.6.1.gz".as_bytes()).unwrap();
    let mut s = String::new();

    d.read_to_string(&mut s).unwrap();
    println!("{}", s);
}
```

Do you want more information?

**Comment by alexcrichton** [comment]
Is there a location I could download that file from?

**Comment by adjivas** [comment]
I have ***Temporarily*** open this [Github's location](https://github.com/adjivas/flate2-rs_test.git) for you.
You can now found this file at [data/2to3-2.6.1.gz](https://github.com/adjivas/flate2-rs_test/blob/master/data/2to3-2.6.1.gz).

**Comment by alexcrichton** [comment]
Oh oops should have seen this from the code snippet! The argument to `GzDecoder::new` is actually an I/O stream, not a filename, so you'll want to open the file and then pass it in. Right now you're actually creating a decoder which is attempting to decode the literal byte string of the file name, which may not be what you want!

Thanks for the report though!

**Comment by adjivas** [comment]
I best understand this incident now! Thank you for your help and sorry to have not more read the documentation about **I/O stream** because this information is present.

Good continuation @alexcrichton.

**Comment by alexcrichton** [comment]
No worries!

**Comment by HTG-YT** [comment]
Hey there, I am having the same issue and I would like to use the method with a string.

**Comment by HTG-YT** [comment]
Just for a reference, below is my code:
```rust
extern crate base64;
extern crate flate2;

use std::io::prelude::*;
use std::println;

use flate2::read::GzDecoder;

fn initialize() {
    let mut gzip_decoder: GzDecoder<&[u8]> = GzDecoder::new("H4sIAAAAAAAA/1WOzQrCMBCEXynpj+CxJlIW3\
    A3FRum1KiEJ6KFI0zy9CaWit93Z2W/msUBAATsQsGDEAuxswKUpaqtsY9EhxwWmdOfkTKnOm9fMq9dUFIca7ab7r67k8OP3b\
    NWbGdzLjM/LNIq86wLTv5JHlvgMZc49vO/XMJ1EY6kfIjlfYd8VSnaBMq+t+djOuVOFEljqUpLTHF0X/tk+ddMFSZMYukZ3Y\
    xShJrExwv4Dldqe4gABAAA=".as_bytes());
    let mut gzip_decompressed_string: String = String::new();

    gzip_decoder.read_to_string(&mut gzip_decompressed_string).unwrap();
    println!("{}", gzip_decompressed_string);
}
```
