### ISSUE TITLE
Use miniz_oxide by default

### ISSUE THREAD

**Issue by Shnatsel** [alexcrichton/flate2-rs#215]
It seems miniz_oxide backend has matured enough to be the default:

1. Now that `miniz_oxide` backend contains no unsafe code and calls to it no longer go through a C API, it is strictly safer than the default miniz backend.
1. Performance is about the same (oxide decompression is faster, compression is slower).
1. miniz_oxide has received plenty of testing since the popular `reqwest` library uses it exclusively.

Is there anything else needed before flate2 can switch to miniz_oxide by default?

**Comment by alexcrichton** [comment]
Thanks for the nudge, I tend to forget about these long-term migrations! I agree it's likely ready for use, and have posted this as #216
