### ISSUE TITLE
Differences between `rust_backend` and `zlib`

### ISSUE THREAD

**Issue by Erk-** [alexcrichton/flate2-rs#217]
When using the in-memory `Decompress` there are subtle differences between `zlib` and `rust_backend` if you decompress into a buffer not large enough for all the data, while using Sync it will only update the `total_in` method on the `zlib` backend, at least I belive so. I found this issue while using the `total_in` delta as an offset of the input data I had.
Something along the lines of the following:
```rust
let before = self.decompress.total_in();
let mut offset = 0;
loop {
    self.internal_buffer.clear();

    self.decompress.decompress_vec(
        &self.compressed[offset..],
        &mut self.internal_buffer,
        FlushDecompress::Sync,
    )?;

    offset = (self.decompress.total_in() - before)
        .try_into()
        .unwrap_or(0);
    self.buffer.extend_from_slice(&self.internal_buffer[..]);
    if self.internal_buffer.len() < self.internal_buffer.capacity()
        || offset > self.compressed.len()
    {
        break;
    }
}
```

**Comment by Erk-** [comment]
Both the C and Rust version seem to behave in the same way, so this is a difference between miniz and zlib I assume.

**Comment by alexcrichton** [comment]
Ah ok, in that case I think this is probably just something to handle locally, I don't think there's much that can be done in this crate!

The APIs are intentionally very flexible and aren't intended to be the exact same across all implementations.
