### ISSUE TITLE
Yank breaking versions with "*" deps

### ISSUE THREAD

**Issue by kornelski** [alexcrichton/flate2-rs#224]
Some old versions of `flate2` have dependencies specified with `"*"` version requirement (`miniz-sys = "*"`).

Crates with such vague dependency versions became unusable, because `*` allows picking too-new semver-incompatible dependencies.
It also breaks Cargo's `minimal-versions` feature, because `*` requirement allows picking very very old dependencies that aren't compatible with Rust 1.0.

Because these old versions of `flate2` are unusable and cause problems for Cargo, I suggest yanking them:

```bash
cargo yank --vers 0.0.1
cargo yank --vers 0.0.2
cargo yank --vers 0.0.3
```

**Comment by kornelski** [comment]
Same goes for `miniz-sys`:


```bash
cargo yank --vers 0.0.1
cargo yank --vers 0.0.2
```

**Comment by alexcrichton** [comment]
Thanks for the report, but I do not have time to manage extremely old versions of this crate, so I'm going to close this.
