### ISSUE TITLE
Zlib generated fails does not include proper compression header

### ISSUE THREAD

**Issue by otavio** [alexcrichton/flate2-rs#225]
The generated fine does not include the referred compression level.

It should looks like:

```
Level | ZLIB  | GZIP 
  1   | 78 01 | 1F 8B 
  2   | 78 5E | 1F 8B 
  3   | 78 5E | 1F 8B 
  4   | 78 5E | 1F 8B 
  5   | 78 5E | 1F 8B 
  6   | 78 9C | 1F 8B 
  7   | 78 DA | 1F 8B 
  8   | 78 DA | 1F 8B 
  9   | 78 DA | 1F 8B 
```
However, the second byte is always `0x01`. This happens using the `default` feature. Using `zlib` backend it works as expected.

**Comment by alexcrichton** [comment]
Thanks for the report! I think though that this isn't an issue with this library? This library is largely just multiplexing multiple implementations of zlib/deflate, so this would likely be best reported to the respective backends?

**Comment by otavio** [comment]
> Thanks for the report! I think though that this isn't an issue with this library? This library is largely just multiplexing multiple implementations of zlib/deflate, so this would likely be best reported to the respective backends?

You mean the `miniz_oxide`?

**Comment by otavio** [comment]
Reported at https://github.com/Frommi/miniz_oxide/issues/65
