### ISSUE TITLE
backend cloudflare_zlib not working?

### ISSUE THREAD

**Issue by mpetri** [alexcrichton/flate2-rs#229]
I'm trying to use the optimized cloudflare zlib backend but I'm getting the error described below.

I'm trying to follow this instruction:

```
flate2 = { version = "1.0", features = ["cloudflare_zlib"], default-features = false }
```

but I'm getting the error:

```
the package `test` depends on `flate2`, with features: `cloudflare_zlib` but `flate2` does not have these features.
```

**Comment by alexcrichton** [comment]
This feature hasn't yet been published, so it's not available on crates.io yet
