### ISSUE TITLE
cloudflare_zlib feature isn't available on crates.io

### ISSUE THREAD

**Issue by yzsolt** [alexcrichton/flate2-rs#232]
If the `cloudflare_zlib` feature is considered stable, a new minor flate2 release should be issued to make it available in the official package. Then I could use that as a dependency instead of a local flate2-rs clone.

**Comment by yzsolt** [comment]
I see this is a duplicate of https://github.com/alexcrichton/flate2-rs/issues/229, so closing for now.
Is there any info about when will this feature land?

**Comment by alexcrichton** [comment]
Sorry for the delay, should be published now!
