### ISSUE TITLE
GzDecoder doesn't implement the Seek trait ?

### ISSUE THREAD

**Issue by dandyvica** [alexcrichton/flate2-rs#234]
Hi guys,

I didn't see in the documentation a Seek trait implementation for _GzDecoder_. 
Do you plan to develop this one day or is it up to each project to implement it's own ?

I would have need this for gzipped files.

Thanks!

**Comment by alexcrichton** [comment]
I don't believe the gzip format supports seeking, so it's currently intentional that this is not implemented.
