### ISSUE TITLE
When deserializing, flate2 incorrectly declares a file corrupt

### ISSUE THREAD

**Issue by wackywendell** [alexcrichton/flate2-rs#25]
Here is the code that I wanted to run:

```rust
let mut buf : io::BufReader<File> = io::BufReader::new(try!(File::open(path)));
let mut gzbuf = try!(GzDecoder::new(buf));
let decoded = try!(serde_json::de::from_reader(&mut gzbuf));
```

This fails, with the error `corrupt gzip stream does not have a matching checksum`. 

This seems to only occur when deserializing with `serde_json`, so maybe `serde_json` is also at fault, but that error is definitely wrong: there's nothing wrong with the gzip stream.

To show this, I made an entire [repository](https://github.com/wackywendell/gzserde) around this to try and figure it out, and I still haven't quite gotten to the bottom. If you run `cargo test` on that repository, the test [test_gz_basic2b()]() fails, while [test_gz_basic2b()](https://github.com/wackywendell/gzserde/blob/master/src/lib.rs#L158-L169) succeeds.

If this bug is more appropriate to give to serde, please let me know! And also what I should tell them, because this only occurs when using both `serde_json` and `flate2`.

**Comment by alexcrichton** [comment]
Thanks for the report!

**Comment by wackywendell** [comment]
Thanks for the very prompt fix!
