### ISSUE TITLE
Add a way to reuse Readers/Writers

### ISSUE THREAD

**Issue by thinkofdeath** [alexcrichton/flate2-rs#26]
For my case the zlib ones.

Each reader (and I assume Writer) allocates a 32kb buffer internally, it would be nice to have a way to reset an old reader so that we don't have to allocate that buffer every time.
By the looks of it mz_deflateReset exists for this case.

**Comment by alexcrichton** [comment]
Is the use case here that you've got multiple zlib streams concatenated on one stream? It seems like you'd not only want to reset the inner miniz state but also swap out the wrapped I/O stream?

**Comment by thinkofdeath** [comment]
Minecraft's protocol compresses each packet as a separate stream, out of my hands to change it.

And yes swapping out the wrapped stream would be required too for this case. I was thinking something like Go's implementation http://golang.org/pkg/compress/zlib/#Writer.Reset (which exist for both readers and writers)

**Comment by alexcrichton** [comment]
Ok, cool, just wanted to clarify! Could you try out the support added in 0e66bab? If it works out just fine I'll push a new release

**Comment by thinkofdeath** [comment]
Seems to work fine, thanks :)
Is it possible to do the same for decoders or do they not allocate the same buffer?

**Comment by alexcrichton** [comment]
Sure, sounds good to me: https://github.com/alexcrichton/flate2-rs/commit/a930f183166bd77a3ee0574f6cd512fb7bbeef73

**Comment by thinkofdeath** [comment]
Worked perfectly, thanks
