### ISSUE TITLE
About Zlib-sys

### ISSUE THREAD

**Issue by kali** [alexcrichton/flate2-rs#37]
I see you are working on zlib-sys too...

Do you have some kind of long-term goal to replace miniz by zlib ? Or support two backends through features ? Miniz limitations have really been a pain recently.

**Comment by alexcrichton** [comment]
I've thought that it would be pretty easy in the past to support both miniz and zlib as a backend, and I'd be more than willing to accept a PR for that!

Did you run into problems with miniz, however? I'm curious what its limitations are.

**Comment by alexcrichton** [comment]
Actually I was interested in implementing this, so I went ahead and did so!

https://github.com/alexcrichton/flate2-rs/commit/2709c8e921e23aecbfb925bc81b62281c17b273e

**Comment by kali** [comment]
well... this is just great :)

I have had several issues with flate2 due — i think — in part to miniz. zlib being very robust, people do all kind of weird things with their compressed files. Last year, it was a .gz made by concatenating several .gz together. Not in the standard, but zlib accepts it, so everybody does it.

This time it was a deflate-d file that was breaking for some unknown reason. In both occurrences, I had to ressort to piped external process to read the files.

So... thanks a lot.

**Comment by kali** [comment]
FYI, I was wrong, it was not a miniz problem, merely confusing filenames. The files I'm getting are called "deflate" but are actually using the small zlib header. Obviously I was using "deflate_decode()" where I should just have been using the "zlib_decode()".

As my external process, it was just detecting the header and picking the right encapsulation...

A good way to waste time.
