### ISSUE TITLE
ZlibDecoder doesn't have any error checking

### ISSUE THREAD

**Issue by SethDusek** [alexcrichton/flate2-rs#38]
Basically title, if you try to decompress an invalid archive, it won't really tell you anything about whether it's valid or not

**Comment by alexcrichton** [comment]
Do you have some example data that I could test out on? There should be quite a bit of error checking internally, but there may perhaps be a bug here or there.

**Comment by SethDusek** [comment]
```rust
extern crate flate2;

use std::io::prelude::*;
use flate2::read::ZlibDecoder;

fn main() {
    let mut d = ZlibDecoder::new("test".as_bytes());
    let mut string = String::new();
    d.read_to_string(&mut string);
    println!("Here's the data {}",&string); //print's Here's the data + blank
}```

Unlike GzDecoder, ZlibDecoder::new() doesn't return a result and just returns the encoder, so you don't know whether it actually decoded

**Comment by alexcrichton** [comment]
Ah this is actually because the error is being ignored in this example. If you `println!("{:?}", foo)` the result of the `read_to_string` call you'll see:

```
Err(Error { repr: Custom(Custom { kind: InvalidInput, error: StringError("corrupt deflate stream") }) })
```

And during compilation you should also being seeing:

```
src/main.rs:9:5: 9:35 warning: unused result which must be used, #[warn(unused_must_use)] on by default
src/main.rs:9     d.read_to_string(&mut string);
                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

I'm gonna close this for now as it looks like the error is coming out ok, but let me know if you need any more help!

**Comment by SethDusek** [comment]
Oh, thanks
