### ISSUE TITLE
Cargo.toml for miniz-sys should document Unlicense

### ISSUE THREAD

**Issue by joshtriplett** [alexcrichton/flate2-rs#53]
The Cargo.toml file for miniz-sys lists the license as MIT/Apache-2.0; however, miniz.c itself uses the Unlicense.

Since the Unlicense puts the code in the public domain, if you intended to relicense it, you can do so; however, if you didn't intend to relicense it, you should document the original license.

**Comment by alexcrichton** [comment]
I don't really know what to do when it comes to license, but I'd love to ensure that all licenses are abided and what not. What specifically needs to be done here?

**Comment by joshtriplett** [comment]
The easiest fix, if you're fine with putting the rest of the packaging for miniz-sys under the same license as miniz.c itself, would be to change the license field in Cargo.toml to just say "Unlicense" (and drop the LICENSE-* files from the repository).  Alternatively, you could change it to "MIT/Apache-2.0/Unlicense", if you prefer.

**Comment by alexcrichton** [comment]
But all the Rust code is under the "standard Rust license", not the unlicense?

**Comment by joshtriplett** [comment]
@alexcrichton If you want to keep the Rust code under a different license than the C code, then that'd be `(MIT OR Apache-2.0) AND Unlicense`, in SPDX syntax.

Note: I'm not suggesting changing the license expression of flate2; I'm suggesting changing the license expression of miniz-sys.  (That's why one reasonable possibility seemed like putting miniz-sys under the same license as miniz.c.)

**Comment by alexcrichton** [comment]
Ok cool, sounds good to me!

**Comment by joshtriplett** [comment]
Thanks!
