### ISSUE TITLE
miniz-sys makes x86_64-w64-mingw32-* freak out

### ISSUE THREAD

**Issue by nagisa** [alexcrichton/flate2-rs#54]
Compiling a project that transitively depends on flate2. Got a university project to deliver by monday.

Doing it like this:

```
cargo rustc --release --target=x86_64-pc-windows-gnu -- -C linker=x86_64-w64-mingw32-gcc
```

Always works flawless. Not this time. Got linker error instead

```
  = note: collect2: error: ld returned 1 exit status
```

A scary one. Not even a bleept about an undefined reference or some such.

Instead turns out some elfs got into a miniz rlib:

```
$ x86_64-w64-mingw32-objdump  -t "path/target/x86_64-pc-windows-gnu/release/deps/libminiz_sys-f01b4045f82726c9.rlib" 
In archive path/target/x86_64-pc-windows-gnu/release/deps/libminiz_sys-f01b4045f82726c9.rlib:

miniz_sys-f01b4045f82726c9.0.o:     file format pe-x86-64
<snip>
miniz.o:     file format elf64-x86-64
```

**Comment by nagisa** [comment]
What probably happened is `gcc` crate using… `gcc` to compile the `miniz.o`, which is why it ended being an elf.

Making

```
$ echo $CC 
x86_64-w64-mingw32-gcc
```

worked around the issue for the time being. Would be good to figure how to deal with this incompatibility.

**Comment by alexcrichton** [comment]
Could you provide full gists of logs and such? It'd also be helpful to look at the `output` file generated by the miniz-sys crate. As a last ditch attempt you can also enable the `zlib` feature to use `libz-sys` instead which links to the system zlib bindings on MinGW I believe.

Right now miniz-sys uses gcc-rs which [should handle this case automatically](https://github.com/alexcrichton/gcc-rs/blob/dccc656715250a375a34d5470378dbefdab554af/src/lib.rs#L771) but the full logs will help debug this issue to see what's going on.

**Comment by nagisa** [comment]
Right, so it turns out to be another case of me having `$CC` set to `clang` by default. Moving the rant to gcc-rs :)
