### ISSUE TITLE
Library comment contains extra r's

### ISSUE THREAD

**Issue by jorendorff** [alexcrichton/flate2-rs#55]
It says:

```rust
//! This crate consists mainly of two modules, `reader` and `writer`. Each
//! module contains a number of types used to encode and decode various streams
//! of data. All types in the `writer` module work on instances of `Writer`,
//! whereas all types in the `reader` module work on instances of `Reader`.
```

All this stuff has been renamed: `reader` should be `read` etc.

**Comment by alexcrichton** [comment]
Oh dear the age of this library is definitely showing...

Fixed in https://github.com/alexcrichton/flate2-rs/commit/21aa304ee003bd438ccabcb6c33cdd67d6c0c0d1 regardless, thanks for the report!
