### ISSUE TITLE
Documenting BufRead

### ISSUE THREAD

**Issue by P-E-Meunier** [alexcrichton/flate2-rs#58]
I'm trying to read a stream containing several gzip files concatenated.
After some tests, I believe the functions in `bufread::GzDecoder` to read exactly the amount of bytes they need, and `read::GzDecoder` might read more. Apparently, I can call `flate2::bufread::GzDecoder::new` in a loop to get all my files.

However, either I missed something (and I'm sorry), or this is not too explicit in the current documentation. For example, the header of modules `read` and `bufread` appear to be the same, but since `BufRead` inherits `Read`, the two modules seem redundant.

**Comment by alexcrichton** [comment]
The `read` modules are actually mostly for backwards compatibility and convenience at this point.

Seems like a good idea to have docs though! The code would probably look like: https://github.com/alexcrichton/flate2-rs/issues/41#issuecomment-219058833

**Comment by alexcrichton** [comment]
I think this has been handled in the meantime, so I'm going to close.
