### ISSUE TITLE
multi-chunk gzip files are truncated at end of first block

### ISSUE THREAD

**Issue by pmarks** [alexcrichton/flate2-rs#61]
'block' gzip files (see page 10 here: http://samtools.github.io/hts-specs/SAMv1.pdf), are commonly used in bioinformatics.  They are valid gzip files, but use the somewhat rare scheme of storing the data in many consecutive gzip blocks.  System gunzip or zcat will yield all the data in all blocks, however flate2:GzDecoder will only yield data from the first block.  I believe that correct behavior is to continue reading the steam to find another block until EOF.

**Comment by pmarks** [comment]
Here's a small example file with multiple chunks: [small.fastq.gz](https://github.com/alexcrichton/flate2-rs/files/746330/small.fastq.gz)

**Comment by pmarks** [comment]
sorry, dup of #41. closing.

**Comment by alexcrichton** [comment]
Ah yeah this is the same as https://github.com/alexcrichton/flate2-rs/issues/41, but it's common enough that it seems prudent to add something to process these sorts of streams to the library directly. I wouldn't mind adding a helper alongside the existing ones!

**Comment by veldsla** [comment]
What would this helper look like? Apparently it's not #43, because that's been sitting there for quite a while.

**Comment by alexcrichton** [comment]
@veldsla oh my I'm so sorry! That must have fallen out of my inbox by accident, I had no idea that PR was open! I'll review promptly
