### ISSUE TITLE
export crc32 and crc32_combine

### ISSUE THREAD

**Issue by vandenoever** [alexcrichton/flate2-rs#64]
`crc32` and `crc32_combine` are required for reading and writing ZIP files. It would be nice if they are exported by flate2. The alternative for implementations is to use `libz-sys` directly. `

`miniz` does not seem to have a function for combining crc32 values. `crc32_combine` is used in parallel implementations of ZIP where files are divided into pieces and each piece is deflated separately and the deflated partial streams and partial crc32 values are combined in the end.

**Comment by alexcrichton** [comment]
Oh I think that libz/miniz do have crc32 bindings (both) so sounds good to me! Want to send a PR?

**Comment by vandenoever** [comment]
Would it be ok to only expose crc32_combine for zlib because I do not think that miniz has it.

For those interested in how crc32_combine works, here is a good explanation by Mark Adler: http://stackoverflow.com/questions/23122312/crc-calculation-of-a-mostly-static-data-stream/23126768#23126768

**Comment by alexcrichton** [comment]
I believe miniz has it (see `src/crc.rs`)

**Comment by vandenoever** [comment]
I only see `ffi::mz_crc32` in there.

**Comment by alexcrichton** [comment]
Oh ok I see. Yeah in that case it's ok to only expose with zlib or to just implement it in Rust when miniz is in effect.

**Comment by vandenoever** [comment]
flate2 already has a Crc class. Shall I make that public and add a `combine()` function?

**Comment by alexcrichton** [comment]
Seems plausible!

**Comment by vandenoever** [comment]
https://github.com/alexcrichton/flate2-rs/pull/68 is my attempt at adding crc32_combine.

**Comment by alexcrichton** [comment]
Done in https://github.com/alexcrichton/flate2-rs/pull/68
