### ISSUE TITLE
flate2 happily "decompresses" a corrupt gzip file

### ISSUE THREAD

**Issue by dhardy** [alexcrichton/flate2-rs#7]
I have a corrupt gzipped file which "gunzip" fails to decompress with (crc error and length error), but which flate2 happily decompresses (the result is of course corrupt).

My application requires detecting this kind of thing. I can provide a sample file on request but apparently not upload it here.

**Comment by alexcrichton** [comment]
I believe a bug or two in this area has been fixed since this was opened, so I'm going to close this assuming it was fixed.
