### ISSUE TITLE
Example of FlateReader/FlateWriter

### ISSUE THREAD

**Issue by ignatenkobrain** [alexcrichton/flate2-rs#72]
Would be very useful to see some minimal example of those

**Comment by alexcrichton** [comment]
Do you mean FlateReadExt and FlateWriteExt? (if so I definitely agree!)

**Comment by ignatenkobrain** [comment]
```
There are two helper traits provided: FlateReader and FlateWriter. These provide convenience methods for creating a decoder/encoder out of an already existing stream to chain construction.
```

I was mentioning this quote. If I got it correctly, it is about FlateReadExt/FlateWriteExt, no?

**Comment by alexcrichton** [comment]
Oh heh yeah, that's a long outdated comment! But yeah the Ext traits should have examples regardless.

**Comment by alexcrichton** [comment]
Added in https://github.com/alexcrichton/flate2-rs/pull/115
