### ISSUE TITLE
"unknown return code: -2"

### ISSUE THREAD

**Issue by Ereski** [alexcrichton/flate2-rs#73]
I have a `write::ZlibEncoder` which always panicks with `unknown return code: -2` on mem.rs:226. I'm using the zlib backend (zlib v1.2.11, libz-sys 1.0.13) with flate2 v0.2.17.

In zlib's header, error code -2 is `Z_STREAM_ERROR` which means that `the stream state was inconsistent` on a call to `deflate()`. The relevant backtrace is:

>    7:     0x55ecdd79bdc8 - flate2::mem::Compress::compress::h944fc62bd5cc0d94
>                         at /.cargo/registry/src/github.com-1ecc6299db9ec823/flate2-0.2.17/src/mem.rs:226
>    8:     0x55ecdd79bf23 - flate2::mem::Compress::compress_vec::h8e04b6895a662a0e
>                         at /.cargo/registry/src/github.com-1ecc6299db9ec823/flate2-0.2.17/src/mem.rs:251
>    9:     0x55ecdd79b705 - <flate2::mem::Compress as flate2::zio::Ops>::run_vec::h0547d0514c764c38
>                         at /.cargo/registry/src/github.com-1ecc6299db9ec823/flate2-0.2.17/src/zio.rs:31
>   10:     0x55ecdd516ac0 - <flate2::zio::Writer<W, D> as std::io::Write>::write::h52ff979bdb398a3e
>                         at /.cargo/registry/src/github.com-1ecc6299db9ec823/flate2-0.2.17/src/zio.rs:143
>   11:     0x55ecdd5162ab - <flate2::zlib::EncoderWriter<W> as std::io::Write>::write::h8e5590d20a34db48
>                         at /.cargo/registry/src/github.com-1ecc6299db9ec823/flate2-0.2.17/src/zlib.rs:102
>   12:     0x55ecdd47f2ef - std::io::Write::write_all::h95d0008b89f6db59
>                         at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/io/mod.rs:944
>   13:     0x55ecdd48033e - std::io::impls::<impl std::io::Write for &'a mut W>::write_all::hf6742d17386c5ea7
>                         at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/io/impls.rs:51

The code using `ZlibEncoder` is:

```
let mut zlib = ZlibEncoder::new(Vec::new(), Compression::Best);
serde_json::to_writer(&mut zlib, data).unwrap();
zlib.finish().unwrap()
```

The `ZlibEncoder` works flawlessly with the minizip backend

**Comment by alexcrichton** [comment]
Thanks for the report! Do you have some sample data that causes this? (just to add a test case with)

**Comment by Ereski** [comment]
Sorry, but no. Most of the data is transient. I can try finding a minimal test case later today if needed.

**Comment by alexcrichton** [comment]
I wonder if this was maybe fixed by https://github.com/alexcrichton/flate2-rs/pull/69? Could you try testing out the master branch?

**Comment by Ereski** [comment]
Sorry for the delay. Yes, the master branch seems to be working now.
