### ISSUE TITLE
Write usage examples

### ISSUE THREAD

**Issue by dtolnay** [alexcrichton/flate2-rs#76]
The crate-level documentation at https://docs.rs/flate2 as well the documentation for the modules / types / traits / methods should contain examples. Currently the only two pieces of example code are in the readme.

**Comment by dtolnay** [comment]
Remember to use `?`, not `try!` or `unwrap()`, for the examples.

**Comment by AndyGauge** [comment]
Added deflate examples #114

**Comment by brson** [comment]
Thanks @AndyGauge !

**Comment by alexcrichton** [comment]
Finished through multiple PRs by @AndyGauge, thanks so much again!
