### ISSUE TITLE
GzBuilder methods should take Into<Vec<u8>>

### ISSUE THREAD

**Issue by dtolnay** [alexcrichton/flate2-rs#84]
Currently [`GzBuilder::filename`](https://docs.rs/flate2/0.2.17/flate2/struct.GzBuilder.html#method.filename) and [`GzBuilder::comment`](https://docs.rs/flate2/0.2.17/flate2/struct.GzBuilder.html#method.comment) take `&[u8]` while [`GzBuilder::extra`](https://docs.rs/flate2/0.2.17/flate2/struct.GzBuilder.html#method.extra) takes `Vec<u8>`.

These would be more consistent and more usable if they all accepted `Into<Vec<u8>>`.

**Comment by alexcrichton** [comment]
Fixed in #99
