### ISSUE TITLE
Write::write_all is incompatible with non-blocking IO

### ISSUE THREAD

**Issue by sid0** [alexcrichton/flate2-rs#92]
Unfortunately `std::io::Write::write_all` is incompatible with non-blocking IO, because it can fail after a partial write and lose track of how much was written. We appear to use `write_all` in a couple of places. Consider replacing it with something like the `write_from_offset` I [implemented in zstd-rs](https://github.com/gyscos/zstd-rs/blob/master/src/stream/encoder.rs#L256).

**Comment by alexcrichton** [comment]
Yes definitely something I'd like to fix!

I hope to provide a `tokio` feature for this crate soon, which implements `AsyncRead` and `AsyncWrite` for all streams.
