### ISSUE TITLE
Write wrappers should only perform one write per write call

### ISSUE THREAD

**Issue by sid0** [alexcrichton/flate2-rs#93]
[The documentation for `Write::write`](https://doc.rust-lang.org/std/io/trait.Write.html#tymethod.write) says that

> A call to write represents at most one attempt to write to any wrapped object.

The write wrappers at the moment do a `write_all` when `write` is called, which is in violation of this contract.

We would probably need to switch to trying to trying to write from the internal buffer and returning `ErrorKind::Interrupted` if it was successful.

**Comment by alexcrichton** [comment]
Ok I've pushed what I believe should be tokio bindings for this crate (behind an optional feature), mind testing out and seeing if they work for you?
